language: python
python:
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8-dev"
        - "nightly"
install:
        pip install setuptools
script:
        python setup.py test
