name: Argparse_Formatter Tests

on: [push, pull_request]

jobs:
  noxtest:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12.0-alpha - 3.12.0"]
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools codecov pytest-cov pytest
    - name: Run pytests
      run: |
        py.test --cov-report term --cov=argparse_formatter; codecov
